name: Build and Test
on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'liberica'

      - name: Setup Maven
        uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "gemfire-broadcom-repo",
              "username": "${{ secrets.SUPPORT_BROADCOM_COM_USERNAME }}",
              "password": "${{ secrets.SUPPORT_BROADCOM_COM_PASSWORD }}"
            }]

      - name: Build and Test
        shell: bash
        run: |
          ./mvnw compile test