name: Publish

on:
  workflow_dispatch:
  push:
    tags:
    - v*

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'liberica'

    - name: Setup Maven
      uses: s4u/maven-settings-action@v3.1.0
      with:
        githubServer: false
        servers: |
          [{
            "id": "gemfire-broadcom-repo",
            "username": "${{ secrets.SUPPORT_BROADCOM_COM_USERNAME }}",
            "password": "${{ secrets.SUPPORT_BROADCOM_COM_PASSWORD }}"
          },{
            "id": "central",
            "username": "${{ secrets.SONATYPE_ROBOT_USERNAME }}",
            "password": "${{ secrets.SONATYPE_ROBOT_PASSWORD }}"
          }]

    - name: Build and Test
      shell: bash
      env:
        MAVEN_GPG_KEY_FINGERPRINT: ${{ secrets.SIGNING_KEY_ID }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: |
        set -e -o pipefail
        
        echo -n '${{ secrets.SIGNING_KEY_TGZ }}' | base64 -d | tar zxf - -C ${HOME} --exclude '*.lock'
        SIGNING_RC=0
        ./mvnw -DskipTests source:jar javadoc:jar -Pdefault deploy || SIGNING_RC=$?
        rm -rf ${HOME}/.gnupg
        
        exit $SIGNING_RC
        
